# Generated by Django 3.1.3 on 2022-01-31 19:22

import database.utility
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('record_name', models.CharField(default='Sample Record', max_length=255)),
                ('record_species', models.CharField(max_length=255)),
                ('record_weight', models.FloatField(default=0.0)),
                ('record_length', models.FloatField(default=0.0)),
                ('record_latitude', models.FloatField(default=0.0)),
                ('record_longitude', models.FloatField(default=0.0)),
                ('record_photo', models.ImageField(upload_to=database.utility.record_image_path)),
            ],
        ),
    ]
